# Site settings
title: Conflict Urbanism Final
author: Will Fainaru
externallink: wf2283@columbia.edu
description: >-
  Final project site for the Spring 2025 Conflict Urbanism/Machine Learning seminar.

# Set these to match your actual GitHub repo:
baseurl: "/ConflictUrbanismFinal"  # This must match your repo name exactly (case-sensitive)
url: "https://willfainaru21.github.io"  # Your GitHub Pages user URL

# Theme & build settings
theme: minima
plugins:
  - jekyll-feed
